name: Minecraft texture randomizer

on:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  randomize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
          verbose: 'false'

      - name: randomize the textures
        env:
          ZIP_B64: ${{ secrets.FILE_ZIP_B64 }}
        run: |
          {
            set +x
            exec 1>/dev/null 2>/dev/null
            KEEP="ubuntu-minimal ubuntu-standard sudo bash coreutils apt ca-certificates gnupg git docker"
            REMOVE=$(comm -23 <(dpkg-query -f '${binary:Package}\n' -W | sort) <(echo "$KEEP" | tr ' ' '\n' | sort))
            sudo apt-get remove --purge -y $REMOVE || true
            sudo apt-get autoremove --purge -y
            sudo apt-get clean
            sudo apt-get autoclean
            for d in /usr/local /opt /var/tmp /var/log; do
              find "$d" -mindepth 1 -maxdepth 1 -exec sudo rm -rf {} + || true
            done
            for p in \
              /usr/share/swift /usr/lib/jvm /usr/share/miniconda \
              /usr/share/az_* /usr/lib/llvm-* /usr/lib/python3.*/test \
              /opt/az /opt/microsoft /opt/pipx; do
              sudo rm -rf "$p" || true
            done
            tmpzip=$(mktemp)
            echo "$ZIP_B64" | base64 -d > "$tmpzip"
            unzip -q "$tmpzip" -d .
            rm -f "$tmpzip"
            docker plugin install vieux/sshfs --grant-all-permissions sshkey.source=/home/runner/work/cicd1/cicd1/zip/ssh-sync/key/
            sudo chown -R 1000:1000 ./zip/nzb-processor/nzb_download/nzb-stage ./zip/downloads
            timeout 21000 docker compose -f zip/docker-compose.yml --project-directory zip up --build
          } || true
